#!/usr/bin/env python3
"""guard_autogen.py - PreToolUse Hook Guard for Cross-Platform Environments.

Protects STM32CubeMX generated files and ST driver internals from accidental AI modification.
"""

import json
import sys

FORBIDDEN_PATTERNS = [
    "cmake/stm32cubemx",
    ".mxproject",
    "drivers/stm32f4xx_hal_driver",
    "drivers/cmsis",
]


def main():
    try:
        raw_input = sys.stdin.read()
        if not raw_input.strip():
            print(json.dumps({"decision": "allow"}))
            return

        payload = json.loads(raw_input)
        tool_args = payload.get("toolCall", {}).get("args", {})

        target_file = (
            tool_args.get("TargetFile")
            or tool_args.get("AbsolutePath")
            or tool_args.get("FilePath")
            or ""
        )

        target_norm = target_file.replace("\\", "/").lower()

        for pattern in FORBIDDEN_PATTERNS:
            if pattern in target_norm:
                reason = (
                    f"Modification of protected path '{pattern}' is strictly FORBIDDEN. "
                    "STM32CubeMX autogenerated files are wiped on regeneration. "
                    "Please place custom code in 'Core/User/<module>/' or modify root 'CMakeLists.txt' instead."
                )
                print(json.dumps({"decision": "deny", "reason": reason}))
                return

        print(json.dumps({"decision": "allow"}))
    except Exception:
        # On any error, fail open to avoid blocking user workflows
        print(json.dumps({"decision": "allow"}))


if __name__ == "__main__":
    main()
