# guard_autogen.ps1 - PreToolUse Hook Guard for Windows PowerShell
# Protects STM32CubeMX generated files and ST driver internals from accidental AI modification.

$inputJson = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($inputJson)) {
    Write-Output '{"decision": "allow"}'
    exit 0
}

try {
    $payload = $inputJson | ConvertFrom-Json
    $toolCall = $payload.toolCall
    $toolArgs = $toolCall.args

    $targetFile = ""
    if ($toolArgs.TargetFile) { $targetFile = $toolArgs.TargetFile }
    elseif ($toolArgs.AbsolutePath) { $targetFile = $toolArgs.AbsolutePath }
    elseif ($toolArgs.FilePath) { $targetFile = $toolArgs.FilePath }

    $targetNorm = $targetFile.Replace('\', '/').ToLower()
    $forbidden = @(
        "cmake/stm32cubemx",
        ".mxproject",
        "drivers/stm32f4xx_hal_driver",
        "drivers/cmsis"
    )

    foreach ($pattern in $forbidden) {
        if ($targetNorm.Contains($pattern)) {
            $reason = "Modification of autogenerated / vendor protected path '$pattern' is strictly FORBIDDEN. STM32CubeMX autogenerated files are wiped and regenerated. Please place custom code in 'Core/User/<module>/' or modify root 'CMakeLists.txt' instead."
            $res = [PSCustomObject]@{
                decision = "deny"
                reason = $reason
            }
            Write-Output ($res | ConvertTo-Json -Compress)
            exit 0
        }
    }

    Write-Output '{"decision": "allow"}'
}
catch {
    Write-Output '{"decision": "allow"}'
}
